export const HOME  = '/home'
export const LOGIN  = '/login'
export const REGISTER = '/register'
export const PRIVATE  = '/private'

export const LOGOUT  = '/private/logout'

export const PROFILE = '/private/profile'
export const BLOG  = '/private/blog'
export const USER  = '/private/user'
export const PRUEBA  = '/private/prueba'
export const PRUEBA2  = '/private/prueba2'
export const POSTR  = '/private/post'
export const UPDATER  = '/private/postUpdates'
export const SHOWPOSTR  = '/private/postShowRecipe/:id'
export const UPLOADTEST = '/private/uploadTest'
export const GPOST = '/private/gpost'
export const EDITGPOST = '/private/editGPost'
export const REVIEWPOST = '/private/newreview'
export const EDITREVIEWPOST = '/private/editreview'
export const MARKETLIST = '/private/marketlist'
export const NEWLIST = '/private/newlist'
export const EDITLIST = '/private/editlist/:id'
export const VIEWMARKETLIST = '/private/viewlist/:id'
export const CALENDAR = '/private/calendar'


